name: BRIGHTON BALLET THEATER
favicon: null
layout_spectrum: 0.24814
typography_spectrum: 0.00465
title: School of Russian American Ballet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c25991'
    - '#63153c'
    - '#000000'
    - '#bb869a'
    - '#dab2c5'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
