name: BRIGHTON BALLET
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1255805012769997
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a0506f'
    - '#ae788f'
    - '#ccbacb'
    - '#111813'
    - '#383639'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
